### ISSUE TITLE
[Icon Request]: Dahua

### ISSUE THREAD

**Issue by warheat1990** [walkxhub/dashboard-icons#147]
**What is the name of the icon(s)?**
Dahua

**What is the website/page of the icon(s)?**
https://www.dahuasecurity.com/

**Upload the icon(s) here: [Optional]**
![Dahua_Technology_logo](https://user-images.githubusercontent.com/4485011/178278483-e4d43995-2f9e-4546-ac64-ddbb7cc2ffaf.svg)

**Comment by walkxcode** [comment]
Do you have a cropped (preferably square) version of this logo?

**Comment by warheat1990** [comment]
How about this one? Doesn't look as good as the SVG version though, color is washed out
![preview-dahua](https://user-images.githubusercontent.com/4485011/178284885-affa10c8-53e9-4abb-b0e5-b7a02d032a67.png)

**Comment by walkxcode** [comment]
This is the same image..?

**Comment by warheat1990** [comment]
yes, just the red color is more washed out on the square version

**Comment by warheat1990** [comment]
Can you also fix the Hikvision as it not square
![image](https://user-images.githubusercontent.com/4485011/178397585-7950f85a-fcaf-4fc2-9509-dca8109b5457.png)
![Hikvision-logo-1](https://user-images.githubusercontent.com/4485011/178397619-b9903139-5c20-421c-a250-e7e6d7f9ffcb.png)

**Comment by deffcolony** [comment]
@warheat1990 

I fixed the **hikvision** logo hope this works:

![Amazing Idea](https://i.imgur.com/LC3xNpH.png)

**Comment by walkxcode** [comment]
Hey, sorry for the delayed response, I was on vacation.

The HIKVISION icon has been updated in the latest release. Please provide a better Dahua icon, as it is still not square.

**Comment by warheat1990** [comment]
> How about this one? Doesn't look as good as the SVG version though, color is washed out ![preview-dahua](https://user-images.githubusercontent.com/4485011/178284885-affa10c8-53e9-4abb-b0e5-b7a02d032a67.png)

I've checked and it's 1024x1024px so it's square.

**Comment by walkxcode** [comment]
I am not referring to the dimensions of the SVG or PNG, but to the logo itself. This (see picture) is what I am referring to. I am looking for a cropped version (maybe only the "da" part?).
![image](https://user-images.githubusercontent.com/71191962/183047632-40026518-4828-4a03-bf3c-a1eb85e8d6ea.png)

**Comment by warheat1990** [comment]
How about this?
![183047632-40026518-4828-4a03-bf3c-a1eb85e8d6ea](https://user-images.githubusercontent.com/4485011/184087381-8a05e9d5-dcd0-4d13-b9ee-68c0de52f448.png)

**Comment by walkxcode** [comment]
That'll work. Thanks!
